import './globals.css'
import { Saira } from 'next/font/google'

import { Header } from '@/components/header'
const saira = Saira({ weight: ['400', '700'], subsets: ['latin'] })

export const metadata = {
  title: 'Capputeeno Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
